execute pathogen#infect()
syntax on
filetype plugin indent on
let g:syntastic_puppet_checkers=['puppet', 'puppetlint']
set listchars=trail:.
set list
set ruler
let g:syntastic_puppet_puppetlint_args='--no-documentation-check --no-80chars-check --no-autoloader_layout-check'
